from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		
		self.QTabWidget2.addTab(self.t21,"Tab 1")
		self.QTabWidget2.addTab(self.t10,"Tab 2")
		self.t21.Height=self.QTabWidget2.Height
		self.t21.Width=self.QTabWidget2.Width
		self.t10.Height=self.QTabWidget2.Height
		self.t10.Width=self.QTabWidget2.Width

		aa=0
	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'Width': '305', 'Tag': 'Activex', 'Visible': 'True', 'Var': '', 'Help': '', 'Events': [], 'Left': '638', 'Enable': 'True', 'Height': '500', 'ParentsType': '', 'Picture': '', 'Name': 't10', 'BackColor': '(1,1,1,0.25)', 'Text': '', 'ForeColor': '(0,0,0,1)', 'Top': '145', 'Font': ''}",'t1','usercontrol',"[]")
		self.createwidget("{'Width': '599', 'Tag': '', 'Visible': 'True', 'Var': '', 'Help': '', 'Events': [], 'Left': '2', 'Enable': 'True', 'Height': '333', 'ParentsType': '', 'Picture': '', 'Name': 'QTabWidget2', 'BackColor': '[0.9411764705882353, 0.792156862745098, 1.0, 1.0]', 'Text': '', 'ForeColor': '(0,0,0,1)', 'Top': '2', 'Font': ''}",'QTabWidget','usercontrol',"[]")
		self.createwidget("{'Width': '468', 'Tag': 'Activex', 'Visible': 'True', 'Var': '', 'Help': '', 'Events': [], 'Left': '57', 'Enable': 'True', 'Height': '446', 'ParentsType': '', 'Picture': '', 'Name': 't21', 'BackColor': '(1,1,1,0.25)', 'Text': '', 'ForeColor': '(0,0,0,1)', 'Top': '372', 'Font': ''}",'t2','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
