from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'dbtype': 'sqllite', 'Enable': 'True', 'Height': '173', 'Text': '', 'Name': 'DataGrid1', 'Visible': 'True', 'Left': '79', 'Width': '318', 'Var': '', 'Tag': 'Activex', 'Events': [[['clicked', 'self,arg1']]], 'Help': '', 'Picture': '', 'Font': '', 'ParentsType': '', 'Top': '49', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,0.25)'}",'DataGrid','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'Enable': 'True', 'Height': '100', 'Text': 'QPushButton1', 'Name': 'QPushButton1', 'Visible': 'True', 'Left': '118', 'Width': '123', 'Var': '', 'Tag': '', 'Events': '[clicked]', 'Help': '', 'Picture': '', 'Font': '', 'ParentsType': '', 'Top': '261', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,0.25)'}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
	def QPushButton1_clicked(self,arg1):
		import sqlite3
		self.db = sqlite3.connect('database.db')
		self.DataGrid1.DataSource(self.db,"select * from supplier limit 10")
		pass

	def DataGrid1_clicked(self,arg1):
		print(arg1.row(),arg1.column(),arg1.data())
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
