from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):	
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(500)#500 ms
		self.sch.Start()
		self.ctlWebsocket21.Open=True
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})
	def activeXcreated(self,*args):
		pass	
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 	
	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):		self.createwidget("{'Help': '', 'Height': '21', 'Visible': 'True', 'Var': '', 'Name': 'ctlWebsocket21', 'Picture': '', 'Text': '', 'ID': 'backbraceesp', 'ClientID': 'qwe', 'BackColor': '(0, 0.5075865711355756, 0.045454875398687755, 0.5)', 'Width': '21', 'ParentsType': '', 'Enable': 'True', 'url': '184.168.126.221:5001', 'Top': '56', 'ForeColor': '(0,0,0,1)', 'Tag': 'Activex', 'Left': '275', 'Font': '', 'Events': [[['on_connected', 'self']], [['on_data_recv', 'self,value']], [['on_error', 'self,value']]]}",'ctlWebsocket2','usercontrol',"[['on_connected', 'self'], ['on_data_recv', 'self,value'], ['on_error', 'self,value']]")
		self.createwidget("{'Help': '', 'Height': '50', 'Visible': 'True', 'Var': '', 'Name': 'Button1', 'Picture': '', 'Text': 'SendClient', 'BackColor': '(1,1,1,1)', 'Width': '100', 'ParentsType': '', 'Enable': 'True', 'Top': '133', 'ForeColor': '(0,0,0,1)', 'Tag': '', 'Left': '285', 'Font': '', 'Events': '[clicked]'}",'QPushButton','usercontrol',"[['clicked', 'self,e'], ['clicked', 'self,arg1'], ['released', 'self']]")
		self.createwidget("{'Help': '', 'Height': '30', 'Visible': 'True', 'Alignment': '', 'Var': '', 'Name': 'Label1', 'Picture': '', 'Text': 'Auto connect to server, set ID and ClientID', 'BackColor': '(1,1,1,1)', 'Width': '100', 'ParentsType': '', 'Enable': 'True', 'Top': '90', 'ForeColor': '(0,0,0,1)', 'Tag': '', 'Left': '505', 'Font': '', 'Events': []}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'Button2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '131', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': '[released]', 'Height': '50', 'Left': '144', 'Tag': '', 'Text': 'QPushButton3', 'Help': ''}",'QPushButton','usercontrol',"[['released', 'self']]")
	def Widget(self):
		return self
	
	def ctlWebsocket21_on_connected(self,conn):
		print("connected")
		pass
	def ctlWebsocket21_on_data_recv(self,value):
		print(value.decode())
		pass
	def ctlWebsocket21_on_error(self,value):
		print(value)
		pass

	def Button1_released(self):
		self.ctlWebsocket21.SendClient("WTANOSTRIPS\r")
	def Button2_released(self):
		self.ctlWebsocket21.SendServer("WTARELAY^456^hey")
		self.ctlWebsocket21.SendServer("WTADEVICES^")
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())