from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'Name': 'QPushButton1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '84', 'Width': '99', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': '[clicked]', 'Height': '24', 'Left': '155', 'Tag': '', 'Text': 'Open File', 'Help': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'Name': 'QFileDialog1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '19', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'False', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '100', 'Left': '39', 'Tag': '', 'Text': '', 'Help': ''}",'QFileDialog','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '19', 'Width': '308', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '154', 'Tag': '', 'Text': 'QLabel2', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'QPushButton3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '84', 'Width': '99', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': '[clicked]', 'Height': '25', 'Left': '261', 'Tag': '', 'Text': 'Save File', 'Help': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'Name': 'QPushButton4', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '141', 'Width': '99', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': '[clicked]', 'Height': '25', 'Left': '38', 'Tag': '', 'Text': 'Select Directory', 'Help': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
	def QPushButton1_clicked(self,arg1):

		self.QFileDialog1.obj.setDirectory(os.path.expanduser('~'))

		name = self.QFileDialog1.getOpenFileName(self, 'Open File')

		self.QLabel2.Text=name[0]
		pass
	def QPushButton3_clicked(self,arg1):

		self.QFileDialog1.obj.setDirectory(os.path.expanduser('~'))

		name = self.QFileDialog1.getSaveFileName(self, 'Open File')

		self.QLabel2.Text=name[0]
		pass
	def QPushButton4_clicked(self,arg1):

		self.QFileDialog1.obj.setDirectory(os.path.expanduser('~'))

		name = self.QFileDialog1.getExistingDirectory()

		self.QLabel2.Text=name
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
