import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Events': '[]', 'Top': '0', 'Text': 'Layout1', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Name': 'Activity', 'Enable': 'True', 'Height': '645', 'Width': '425', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': '', 'Left': '0', 'Tag': ''}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Events': '[]', 'Top': '0', 'Text': 'Layout1', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Name': 'mBase', 'Enable': 'True', 'Height': '645', 'Width': '425', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '0', 'Tag': ''}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Events': '[]', 'Top': '0', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'Image1', 'Enable': 'True', 'Height': '645', 'Width': '425', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': 'MotoNFCDashboard.png', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '0', 'Tag': ''}","Image","mBase","[]")
		self.btnProfile=forms
		self.create("{'Events': '[[, ]]', 'Top': '5', 'Text': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'Name': 'btnProfile', 'Enable': 'True', 'Height': '45', 'Width': '55', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '5', 'Tag': ''}","Layout","mBase","[]")
		self.ProgressPercent=forms
		self.create("{'Events': '[[, ]]', 'Top': '220', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'ProgressPercent', 'Enable': 'True', 'Height': '25', 'Width': '65', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '35', 'Alignment': 'CENTER', 'Tag': ''}","Label","mBase","[]")
		self.btnScan=forms
		self.create("{'Events': '[]', 'Top': '477', 'Text': 'Layout1', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'Name': 'btnScan', 'Enable': 'True', 'Height': '40', 'Width': '110', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '285', 'Tag': ''}","Layout","mBase","[]")
		self.btnDelete=forms
		self.create("{'Events': '[]', 'Top': '520', 'Text': 'Layout1', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'Name': 'btnDelete', 'Enable': 'True', 'Height': '40', 'Width': '110', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '285', 'Tag': ''}","Layout","mBase","[]")
		self.lblMakeModel=forms
		self.create("{'Events': '[]', 'Top': '415', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblMakeModel', 'Enable': 'True', 'Height': '35', 'Width': '280', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '90', 'Alignment': '', 'Tag': ''}","Label","mBase","[]")
		self.lblNFCSerial=forms
		self.create("{'Events': '[]', 'Top': '510', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblNFCSerial', 'Enable': 'True', 'Height': '40', 'Width': '175', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '90', 'Alignment': '', 'Tag': ''}","Label","mBase","[]")
		self.lblEmail=forms
		self.create("{'Events': '[]', 'Top': '334', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblEmail', 'Enable': 'True', 'Height': '25', 'Width': '295', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '100', 'Alignment': 'LEFT', 'Tag': ''}","Label","mBase","[]")
		self.lblNum=forms
		self.create("{'Events': '[]', 'Top': '287', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblNum', 'Enable': 'True', 'Height': '30', 'Width': '315', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '80', 'Alignment': 'LEFT', 'Tag': ''}","Label","mBase","[]")
		self.lblAdd=forms
		self.create("{'Events': '[]', 'Top': '307', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblAdd', 'Enable': 'True', 'Height': '30', 'Width': '270', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '125', 'Alignment': 'LEFT', 'Tag': ''}","Label","mBase","[]")
		self.lblUser=forms
		self.create("{'Events': '[]', 'Top': '75', 'Text': '', 'BackColor': '(1,1,1,1)', 'Name': 'lblUser', 'Enable': 'True', 'Height': '95', 'Width': '80', 'ForeColor': '(0,0,0,1)', 'Font': '', 'Picture': '', 'Help': '', 'Visible': 'True', 'Var': '', 'ParentsType': 'Layout', 'Left': '175', 'Alignment': '', 'Tag': ''}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()