import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '560', 'ParentsType': '', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '90', 'Text': 'Layout1', 'Top': '75', 'Width': '465', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'Activity'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '550', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '0', 'Text': 'Layout1', 'Top': '0', 'Width': '425', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'mBase'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '530', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': 'frmusercontrol.png', 'Help': '', 'Left': '0', 'Text': 'Image1', 'Top': '0', 'Width': '405', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'Tag': '', 'Name': 'Image1'}","Image","mBase","[]")
		self.layLand=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '55', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '130', 'Text': 'Layout1', 'Top': '70', 'Width': '60', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layLand'}","Layout","mBase","[]")
		self.laywater=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '55', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '215', 'Text': 'Layout1', 'Top': '67', 'Width': '60', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'laywater'}","Layout","mBase","[]")
		self.layManual=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '55', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '130', 'Text': 'Layout1', 'Top': '147', 'Width': '60', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layManual'}","Layout","mBase","[]")
		self.layauto=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '55', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '215', 'Text': 'Layout1', 'Top': '147', 'Width': '60', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layauto'}","Layout","mBase","[]")
		self.laySweep=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '55', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '245', 'Text': 'Layout1', 'Top': '402', 'Width': '60', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'laySweep'}","Layout","mBase","[]")
		self.layUp=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '110', 'Text': 'Layout1', 'Top': '382', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layUp'}","Layout","mBase","[]")
		self.layLeft=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '65', 'Text': 'Layout1', 'Top': '417', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layLeft'}","Layout","mBase","[]")
		self.layRight=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '155', 'Text': 'Layout1', 'Top': '417', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layRight'}","Layout","mBase","[]")
		self.layBT=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '185', 'Text': 'Layout1', 'Top': '492', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layBT'}","Layout","mBase","[]")
		self.layDown=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '110', 'Text': 'Layout1', 'Top': '452', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layDown'}","Layout","mBase","[]")
		self.Layout1=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '20', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '105', 'Text': 'Layout1', 'Top': '242', 'Width': '230', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'Layout1'}","Layout","mBase","[]")
		self.lblclass=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '15', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '0', 'Text': 'Label1', 'Top': '0', 'Alignment': '', 'Width': '210', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'Tag': '', 'Name': 'lblclass'}","Label","Layout1","[]")
		self.Layout2=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '20', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '190', 'Text': 'Layout1', 'Top': '300', 'Width': '165', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'Layout2'}","Layout","mBase","[]")
		self.lblplastic=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '15', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '0', 'Text': 'Label2', 'Top': '0', 'Alignment': '', 'Width': '145', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'Tag': '', 'Name': 'lblplastic'}","Label","Layout2","[]")
		self.Layout4=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '20', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '215', 'Text': 'Layout1', 'Top': '320', 'Width': '165', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'Layout4'}","Layout","mBase","[]")
		self.lblnonplastic=forms
		self.create("{'Events': '[[, ]]', 'ForeColor': '(0,0,0,1)', 'Height': '15', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '0', 'Text': 'Label4', 'Top': '0', 'Alignment': '', 'Width': '145', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'Tag': '', 'Name': 'lblnonplastic'}","Label","Layout4","[]")
		self.layLBIN=forms
		self.create("{'Events': '[]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '255', 'Text': 'Layout1', 'Top': '467', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layLBIN'}","Layout","mBase","[]")
		self.layRBIN=forms
		self.create("{'Events': '[]', 'ForeColor': '(0,0,0,1)', 'Height': '35', 'ParentsType': 'Layout', 'Enable': 'True', 'Font': '', 'Var': '', 'Picture': '', 'Help': '', 'Left': '310', 'Text': 'Layout1', 'Top': '467', 'Width': '40', 'BackColor': '(0, 0.46408763670477793, 0.9683289600391486, 0.5)', 'Visible': 'True', 'Tag': '', 'Name': 'layRBIN'}","Layout","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()