import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Tag': '', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Var': '', 'Picture': '', 'Enable': 'True', 'Text': 'Layout1', 'Name': 'Activity', 'Left': '90', 'ParentsType': '', 'Width': '455', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '580', 'Top': '75', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Tag': '', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Var': '', 'Picture': '', 'Enable': 'True', 'Text': 'Layout1', 'Name': 'mBase', 'Left': '5', 'ParentsType': 'Layout', 'Width': '405', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '530', 'Top': '25', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Tag': '', 'BackColor': '(1,1,1,1)', 'Var': '', 'Picture': '1.png', 'Enable': 'True', 'Text': '', 'Name': 'Image1', 'Left': '0', 'ParentsType': 'Layout', 'Width': '405', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '530', 'Top': '0', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Image","mBase","[]")
		self.btnSignIn=forms
		self.create("{'Tag': '', 'BackColor': '(0, 0.4459500369324376, 0.37783847174455243, 0.5)', 'Var': '', 'Picture': '', 'Enable': 'True', 'Text': '', 'Name': 'btnSignIn', 'Left': '60', 'ParentsType': 'Layout', 'Width': '290', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '30', 'Top': '425', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Layout","mBase","[]")
		self.txtID=forms
		self.create("{'Tag': '', 'BackColor': '(1,1,1,1)', 'Var': '', 'Picture': '', 'Enable': 'True', 'Text': '', 'Alignment': '', 'Name': 'txtID', 'Left': '60', 'ParentsType': 'Layout', 'Width': '285', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '50', 'Top': '315', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Entry","mBase","[]")
		self.txtPassword=forms
		self.create("{'Tag': '', 'BackColor': '(1,1,1,1)', 'Var': '', 'Picture': '', 'Enable': 'True', 'Text': '', 'Alignment': '', 'Name': 'txtPassword', 'Left': '60', 'ParentsType': 'Layout', 'Width': '285', 'Events': '[]', 'Help': '', 'Visible': 'True', 'Height': '35', 'Top': '370', 'ForeColor': '(0,0,0,1)', 'Font': ''}","Entry","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()