import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Left': '50', 'Help': '', 'Width': '643', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Visible': 'True', 'ParentsType': '', 'Events': '[[, ]]', 'Var': '', 'Top': '30', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Activity', 'Text': 'Layout1', 'Height': '541', 'Font': ''}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Left': '55', 'Help': '', 'Width': '444', 'BackColor': '(1.00,1.00,1.00,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '35', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'mBase', 'Text': 'Layout2', 'Height': '520', 'Font': ''}","Layout","Activity","[]")
		import Timer
		self.Timer1=Timer.Handler
		self.create("{'Left': '320', 'Interval': '1000', 'Help': '', 'Width': '30', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '335', 'Enable': 'True', 'Tag': 'Activex', 'ForeColor': '(0,0,0,1)', 'Picture': 'Timer.png', 'Name': 'Timer1', 'Text': 'Timer1', 'Height': '30', 'Font': ''}","Timer","mBase","[]")
		import Timer
		self.mytimer=Timer.Handler
		self.create("{'Left': '275', 'Interval': '1000', 'Help': '', 'Width': '30', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '335', 'Enable': 'True', 'Tag': 'Activex', 'ForeColor': '(0,0,0,1)', 'Picture': 'Timer.png', 'Name': 'mytimer', 'Text': 'Timer2', 'Height': '30', 'Font': ''}","Timer","mBase","[]")
		self.Image1=forms
		self.create("{'Left': '315', 'Help': '', 'Width': '85', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '280', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Image1', 'Text': 'Image1', 'Height': '50', 'Font': ''}","Image","mBase","[]")
		self.Button1=forms
		self.create("{'Left': '55', 'Help': '', 'Width': '100', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '300', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Button1', 'Text': 'Button1', 'Height': '50', 'Font': ''}","Button","mBase","[]")
		self.Button2=forms
		self.create("{'Left': '170', 'Help': '', 'Width': '100', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '300', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Button2', 'Text': 'Connect BT', 'Height': '50', 'Font': ''}","Button","mBase","[]")
		self.Label1=forms
		self.create("{'Left': '55', 'Alignment': '', 'Help': '', 'Width': '345', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '30', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label1', 'Text': 'Power Logger App', 'Height': '70', 'Font': ''}","Label","mBase","[]")
		self.Label2=forms
		self.create("{'Left': '55', 'Alignment': '', 'Help': '', 'Width': '220', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '125', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label2', 'Text': 'V', 'Height': '30', 'Font': ''}","Label","mBase","[]")
		self.Label3=forms
		self.create("{'Left': '55', 'Alignment': '', 'Help': '', 'Width': '220', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '165', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label3', 'Text': 'A', 'Height': '30', 'Font': ''}","Label","mBase","[]")
		self.Label4=forms
		self.create("{'Left': '55', 'Alignment': '', 'Help': '', 'Width': '220', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '200', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label4', 'Text': 'W', 'Height': '30', 'Font': ''}","Label","mBase","[]")
		self.Label5=forms
		self.create("{'Left': '55', 'Alignment': '', 'Help': '', 'Width': '220', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '240', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label5', 'Text': 'WH', 'Height': '30', 'Font': ''}","Label","mBase","[]")
		self.Button3=forms
		self.create("{'Left': '55', 'Help': '', 'Width': '80', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '360', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Button3', 'Text': 'Button3', 'Height': '35', 'Font': ''}","Button","mBase","[]")
		self.Layout1=forms
		self.create("{'Left': '115', 'Help': '', 'Width': '75', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '405', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Layout1', 'Text': 'Layout1', 'Height': '40', 'Font': ''}","Layout","mBase","[]")
		self.Label6=forms
		self.create("{'Left': '25', 'Alignment': '', 'Help': '', 'Width': '20', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '5', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label6', 'Text': '^', 'Height': '25', 'Font': ''}","Label","Layout1","[]")
		self.Layout2=forms
		self.create("{'Left': '115', 'Help': '', 'Width': '75', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '455', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Layout2', 'Text': 'v', 'Height': '40', 'Font': ''}","Layout","mBase","[]")
		self.Label7=forms
		self.create("{'Left': '25', 'Alignment': '', 'Help': '', 'Width': '20', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '5', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label7', 'Text': 'v', 'Height': '25', 'Font': ''}","Label","Layout2","[]")
		self.Layout3=forms
		self.create("{'Left': '40', 'Help': '', 'Width': '60', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '430', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Layout3', 'Text': 'Layout1', 'Height': '40', 'Font': ''}","Layout","mBase","[]")
		self.Label8=forms
		self.create("{'Left': '25', 'Alignment': '', 'Help': '', 'Width': '15', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '5', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label8', 'Text': '<', 'Height': '25', 'Font': ''}","Label","Layout3","[]")
		self.Layout4=forms
		self.create("{'Left': '205', 'Help': '', 'Width': '70', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '430', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Layout4', 'Text': 'Layout1', 'Height': '40', 'Font': ''}","Layout","mBase","[]")
		self.Label9=forms
		self.create("{'Left': '20', 'Alignment': '', 'Help': '', 'Width': '25', 'BackColor': '(1,1,1,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Events': '[[, ]]', 'Var': '', 'Top': '5', 'Enable': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Name': 'Label9', 'Text': '>', 'Height': '25', 'Font': ''}","Label","Layout4","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()