import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Enable': 'True', 'Name': 'Activity', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '-5', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': '', 'Left': '75', 'Font': '', 'Width': '643', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Height': '541'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Enable': 'True', 'Name': 'mBase', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '15', 'Text': 'Layout2', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '30', 'Font': '', 'Width': '444', 'Picture': '', 'Help': '', 'BackColor': '(1.00,1.00,1.00,1)', 'Height': '520'}","Layout","Activity","[]")
		import Timer
		self.Timer1=Timer.Handler
		self.create("{'Enable': 'True', 'Name': 'Timer1', 'Var': '', 'Tag': 'Activex', 'Events': '[[, ]]', 'Top': '340', 'Interval': '1000', 'Text': 'Timer1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '360', 'Font': '', 'Width': '30', 'Picture': 'Timer.png', 'Help': '', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Height': '30'}","Timer","mBase","[]")
		import Timer
		self.mytimer=Timer.Handler
		self.create("{'Enable': 'True', 'Name': 'mytimer', 'Var': '', 'Tag': 'Activex', 'Events': '[[, ]]', 'Top': '340', 'Interval': '1000', 'Text': 'Timer2', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '30', 'Picture': 'Timer.png', 'Help': '', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Height': '30'}","Timer","mBase","[]")
		self.Image1=forms
		self.create("{'Enable': 'True', 'Name': 'Image1', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '355', 'Text': 'Image1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '190', 'Font': '', 'Width': '85', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '50'}","Image","mBase","[]")
		self.Button1=forms
		self.create("{'Enable': 'True', 'Name': 'Button1', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '300', 'Text': 'Button1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '100', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '50'}","Button","mBase","[]")
		self.Button2=forms
		self.create("{'Enable': 'True', 'Name': 'Button2', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '300', 'Text': 'Connect BT', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '170', 'Font': '', 'Width': '100', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '50'}","Button","mBase","[]")
		self.Label1=forms
		self.create("{'Enable': 'True', 'Name': 'Label1', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '30', 'Text': 'Power Logger App', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '345', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '70'}","Label","mBase","[]")
		self.Label2=forms
		self.create("{'Enable': 'True', 'Name': 'Label2', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '125', 'Text': 'V', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '220', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Label","mBase","[]")
		self.Label3=forms
		self.create("{'Enable': 'True', 'Name': 'Label3', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '165', 'Text': 'A', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '220', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Label","mBase","[]")
		self.Label4=forms
		self.create("{'Enable': 'True', 'Name': 'Label4', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '200', 'Text': 'W', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '220', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Label","mBase","[]")
		self.Label5=forms
		self.create("{'Enable': 'True', 'Name': 'Label5', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '240', 'Text': 'WH', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '220', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Label","mBase","[]")
		self.Button3=forms
		self.create("{'Enable': 'True', 'Name': 'Button3', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '360', 'Text': 'Button3', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '55', 'Font': '', 'Width': '80', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.Layout1=forms
		self.create("{'Enable': 'True', 'Name': 'Layout1', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '405', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '115', 'Font': '', 'Width': '75', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label6=forms
		self.create("{'Enable': 'True', 'Name': 'Label6', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': '^', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '20', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout1","[]")
		self.Layout2=forms
		self.create("{'Enable': 'True', 'Name': 'Layout2', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '455', 'Text': 'v', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '115', 'Font': '', 'Width': '75', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label7=forms
		self.create("{'Enable': 'True', 'Name': 'Label7', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': 'v', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '20', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout2","[]")
		self.Layout3=forms
		self.create("{'Enable': 'True', 'Name': 'Layout3', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '430', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '40', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label8=forms
		self.create("{'Enable': 'True', 'Name': 'Label8', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': '<', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '15', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout3","[]")
		self.Layout4=forms
		self.create("{'Enable': 'True', 'Name': 'Layout4', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '430', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '205', 'Font': '', 'Width': '70', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label9=forms
		self.create("{'Enable': 'True', 'Name': 'Label9', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': '>', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '20', 'Font': '', 'Width': '25', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout4","[]")
		self.Layout5=forms
		self.create("{'Enable': 'True', 'Name': 'Layout5', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '425', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label10=forms
		self.create("{'Enable': 'True', 'Name': 'Label10', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': 'Label10', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '15', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout5","[]")
		self.Layout6=forms
		self.create("{'Enable': 'True', 'Name': 'Layout6', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '465', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label11=forms
		self.create("{'Enable': 'True', 'Name': 'Label11', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': 'Label11', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '15', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout6","[]")
		self.Layout7=forms
		self.create("{'Enable': 'True', 'Name': 'Layout7', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '425', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '355', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label12=forms
		self.create("{'Enable': 'True', 'Name': 'Label12', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': 'Label12', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '15', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout7","[]")
		self.Layout8=forms
		self.create("{'Enable': 'True', 'Name': 'Layout8', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '465', 'Text': 'Layout1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '355', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Height': '40'}","Layout","mBase","[]")
		self.Label13=forms
		self.create("{'Enable': 'True', 'Name': 'Label13', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '5', 'Text': 'Label13', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '25', 'Font': '', 'Width': '15', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '25'}","Label","Layout8","[]")
		self.txts11=forms
		self.create("{'Enable': 'True', 'Name': 'txts11', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '115', 'Text': '0', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.txts12=forms
		self.create("{'Enable': 'True', 'Name': 'txts12', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '115', 'Text': '180', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '350', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.btnservo11=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo11', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '150', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.btnservo12=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo12', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '152', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '349', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.btnservo22=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo22', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '65', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '355', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.btnservo21=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo21', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '65', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.txts22=forms
		self.create("{'Enable': 'True', 'Name': 'txts22', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '30', 'Text': '180', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '355', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.txts21=forms
		self.create("{'Enable': 'True', 'Name': 'txts21', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '30', 'Text': '0', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.txts31=forms
		self.create("{'Enable': 'True', 'Name': 'txts31', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '195', 'Text': '0', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '284', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.txts32=forms
		self.create("{'Enable': 'True', 'Name': 'txts32', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '195', 'Text': '180', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '349', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.btnservo31=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo31', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '230', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '284', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.btnservo32=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo32', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '232', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '349', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.txts41=forms
		self.create("{'Enable': 'True', 'Name': 'txts41', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '270', 'Text': '0', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.txts42=forms
		self.create("{'Enable': 'True', 'Name': 'txts42', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Alignment': '', 'Top': '265', 'Text': '180', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '350', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '30'}","Entry","mBase","[]")
		self.btnservo42=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo42', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '305', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '350', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
		self.btnservo41=forms
		self.create("{'Enable': 'True', 'Name': 'btnservo41', 'Var': '', 'Tag': '', 'Events': '[[, ]]', 'Top': '307', 'Text': '1', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'ParentsType': 'Layout', 'Left': '285', 'Font': '', 'Width': '60', 'Picture': '', 'Help': '', 'BackColor': '(1,1,1,1)', 'Height': '35'}","Button","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()