import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Picture': '', 'Height': '541', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Text': 'Layout1', 'Width': '643', 'Left': '75', 'ParentsType': '', 'Top': '-5', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Activity'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Picture': '', 'Height': '520', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1.00,1.00,1.00,1)', 'Text': 'Layout2', 'Width': '444', 'Left': '30', 'ParentsType': 'Layout', 'Top': '15', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'mBase'}","Layout","Activity","[]")
		import Timer
		self.Timer1=Timer.Handler
		self.create("{'Picture': 'Timer.png', 'Height': '30', 'Help': '', 'Interval': '1000', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Text': 'Timer1', 'Width': '30', 'Left': '360', 'ParentsType': 'Layout', 'Top': '340', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': 'Activex', 'Enable': 'True', 'Name': 'Timer1'}","Timer","mBase","[]")
		import Timer
		self.mytimer=Timer.Handler
		self.create("{'Picture': 'Timer.png', 'Height': '30', 'Help': '', 'Interval': '1000', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Text': 'Timer2', 'Width': '30', 'Left': '285', 'ParentsType': 'Layout', 'Top': '340', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': 'Activex', 'Enable': 'True', 'Name': 'mytimer'}","Timer","mBase","[]")
		self.Image1=forms
		self.create("{'Picture': '', 'Height': '50', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Image1', 'Width': '85', 'Left': '190', 'ParentsType': 'Layout', 'Top': '355', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Image1'}","Image","mBase","[]")
		self.Button1=forms
		self.create("{'Picture': '', 'Height': '50', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Button1', 'Width': '100', 'Left': '55', 'ParentsType': 'Layout', 'Top': '300', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Button1'}","Button","mBase","[]")
		self.Button2=forms
		self.create("{'Picture': '', 'Height': '50', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Connect BT', 'Width': '100', 'Left': '170', 'ParentsType': 'Layout', 'Top': '300', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Button2'}","Button","mBase","[]")
		self.Label1=forms
		self.create("{'Picture': '', 'Height': '70', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Power Logger App', 'Width': '345', 'Left': '55', 'ParentsType': 'Layout', 'Top': '30', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label1'}","Label","mBase","[]")
		self.Label2=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'V', 'Width': '220', 'Left': '55', 'ParentsType': 'Layout', 'Top': '125', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label2'}","Label","mBase","[]")
		self.Label3=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'A', 'Width': '220', 'Left': '55', 'ParentsType': 'Layout', 'Top': '165', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label3'}","Label","mBase","[]")
		self.Label4=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'W', 'Width': '220', 'Left': '55', 'ParentsType': 'Layout', 'Top': '200', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label4'}","Label","mBase","[]")
		self.Label5=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'WH', 'Width': '220', 'Left': '55', 'ParentsType': 'Layout', 'Top': '240', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label5'}","Label","mBase","[]")
		self.Button3=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Button3', 'Width': '80', 'Left': '55', 'ParentsType': 'Layout', 'Top': '360', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Button3'}","Button","mBase","[]")
		self.Layout1=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '75', 'Left': '115', 'ParentsType': 'Layout', 'Top': '405', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout1'}","Layout","mBase","[]")
		self.Label6=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '^', 'Width': '20', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label6'}","Label","Layout1","[]")
		self.Layout2=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'v', 'Width': '75', 'Left': '115', 'ParentsType': 'Layout', 'Top': '455', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout2'}","Layout","mBase","[]")
		self.Label7=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'v', 'Width': '20', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label7'}","Label","Layout2","[]")
		self.Layout3=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '60', 'Left': '40', 'ParentsType': 'Layout', 'Top': '430', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout3'}","Layout","mBase","[]")
		self.Label8=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '<', 'Width': '15', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label8'}","Label","Layout3","[]")
		self.Layout4=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '70', 'Left': '205', 'ParentsType': 'Layout', 'Top': '430', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout4'}","Layout","mBase","[]")
		self.Label9=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '>', 'Width': '25', 'Left': '20', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label9'}","Label","Layout4","[]")
		self.Layout5=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '425', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout5'}","Layout","mBase","[]")
		self.Label10=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Label10', 'Width': '15', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label10'}","Label","Layout5","[]")
		self.Layout6=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '465', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout6'}","Layout","mBase","[]")
		self.Label11=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Label11', 'Width': '15', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label11'}","Label","Layout6","[]")
		self.Layout7=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '60', 'Left': '355', 'ParentsType': 'Layout', 'Top': '425', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout7'}","Layout","mBase","[]")
		self.Label12=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Label12', 'Width': '15', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label12'}","Label","Layout7","[]")
		self.Layout8=forms
		self.create("{'Picture': '', 'Height': '40', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Text': 'Layout1', 'Width': '60', 'Left': '355', 'ParentsType': 'Layout', 'Top': '465', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Layout8'}","Layout","mBase","[]")
		self.Label13=forms
		self.create("{'Picture': '', 'Height': '25', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': 'Label13', 'Width': '15', 'Left': '25', 'ParentsType': 'Layout', 'Top': '5', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'Label13'}","Label","Layout8","[]")
		self.txts11=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '0', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '115', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts11'}","Entry","mBase","[]")
		self.txts12=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '180', 'Width': '60', 'Left': '350', 'ParentsType': 'Layout', 'Top': '115', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts12'}","Entry","mBase","[]")
		self.btnservo11=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '150', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo11'}","Button","mBase","[]")
		self.btnservo12=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '349', 'ParentsType': 'Layout', 'Top': '152', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo12'}","Button","mBase","[]")
		self.btnservo22=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '355', 'ParentsType': 'Layout', 'Top': '65', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo22'}","Button","mBase","[]")
		self.btnservo21=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '65', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo21'}","Button","mBase","[]")
		self.txts22=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '180', 'Width': '60', 'Left': '355', 'ParentsType': 'Layout', 'Top': '30', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts22'}","Entry","mBase","[]")
		self.txts21=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '0', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '30', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts21'}","Entry","mBase","[]")
		self.txts31=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '0', 'Width': '60', 'Left': '284', 'ParentsType': 'Layout', 'Top': '195', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts31'}","Entry","mBase","[]")
		self.txts32=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '180', 'Width': '60', 'Left': '349', 'ParentsType': 'Layout', 'Top': '195', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts32'}","Entry","mBase","[]")
		self.btnservo31=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '284', 'ParentsType': 'Layout', 'Top': '230', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo31'}","Button","mBase","[]")
		self.btnservo32=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '349', 'ParentsType': 'Layout', 'Top': '232', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo32'}","Button","mBase","[]")
		self.txts41=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '0', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '270', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts41'}","Entry","mBase","[]")
		self.txts42=forms
		self.create("{'Picture': '', 'Height': '30', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '180', 'Width': '60', 'Left': '350', 'ParentsType': 'Layout', 'Top': '265', 'Events': '[[, ]]', 'Alignment': '', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'txts42'}","Entry","mBase","[]")
		self.btnservo42=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '350', 'ParentsType': 'Layout', 'Top': '305', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo42'}","Button","mBase","[]")
		self.btnservo41=forms
		self.create("{'Picture': '', 'Height': '35', 'Help': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Text': '1', 'Width': '60', 'Left': '285', 'ParentsType': 'Layout', 'Top': '307', 'Events': '[[, ]]', 'Visible': 'True', 'Font': '', 'Tag': '', 'Enable': 'True', 'Name': 'btnservo41'}","Button","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()