import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Left': '5', 'Tag': '', 'Events': '[]', 'Name': 'Activity', 'Font': '', 'ParentsType': '', 'Text': 'Layout1', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '405', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '45', 'Height': '655', 'Enable': 'True', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Left': '0', 'Tag': '', 'Events': '[]', 'Name': 'mBase', 'Font': '', 'ParentsType': 'Layout', 'Text': 'Layout1', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '405', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '0', 'Height': '655', 'Enable': 'True', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Left': '0', 'Tag': '', 'Events': '[]', 'Name': 'Image1', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': 'HomeModule-809c8.png', 'ForeColor': '(0,0,0,1)', 'Width': '405', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '0', 'Height': '655', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","Image","mBase","[]")
		self.btnProfile=forms
		self.create("{'Left': '20', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnProfile', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '55', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '5', 'Height': '45', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnQr=forms
		self.create("{'Left': '337', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnQr', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '55', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '7', 'Height': '45', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnSchedule=forms
		self.create("{'Left': '212', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnSchedule', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '170', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '127', 'Height': '35', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnUpload=forms
		self.create("{'Left': '322', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnUpload', 'Font': '', 'ParentsType': 'Layout', 'Text': 'Layout2', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '45', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '197', 'Height': '40', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnAppointments=forms
		self.create("{'Left': '152', 'Tag': '', 'Events': '[]', 'Name': 'btnAppointments', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '105', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '277', 'Height': '70', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnHotline=forms
		self.create("{'Left': '280', 'Tag': '', 'Events': '[]', 'Name': 'btnHotline', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '100', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '277', 'Height': '70', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnUpdates=forms
		self.create("{'Left': '165', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnUpdates', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '90', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '607', 'Height': '45', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.btnLogs=forms
		self.create("{'Left': '315', 'Tag': '', 'Events': '[[, ]]', 'Name': 'btnLogs', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '90', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '607', 'Height': '45', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.lblName=forms
		self.create("{'Left': '20', 'Alignment': '', 'Tag': '', 'Events': '[[, ]]', 'Name': 'lblName', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '365', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '65', 'Height': '60', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","Label","mBase","[]")
		self.lblProgress=forms
		self.create("{'Left': '35', 'Alignment': '', 'Tag': '', 'Events': '[[, ]]', 'Name': 'lblProgress', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '275', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '195', 'Height': '25', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","Label","mBase","[]")
		self.progressBar=forms
		self.create("{'Left': '35', 'Alignment': '', 'Tag': '', 'Events': '[[, ]]', 'Name': 'progressBar', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '335', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '245', 'Height': '20', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","Label","mBase","[]")
		self.pDocList=forms
		self.create("{'Left': '25', 'Tag': '', 'Events': '[[, ]]', 'Name': 'pDocList', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '355', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '375', 'Height': '210', 'Enable': 'True', 'BackColor': '(0.00,0.00,0.00,1)'}","ListBox","mBase","[]")
		self.ProgressPercent=forms
		self.create("{'Left': '35', 'Alignment': 'CENTER', 'Tag': '', 'Events': '[[, ]]', 'Name': 'ProgressPercent', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '65', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '220', 'Height': '25', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","Label","mBase","[]")
		self.btnMedications=forms
		self.create("{'Left': '25', 'Tag': '', 'Events': '[]', 'Name': 'btnMedications', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '105', 'Visible': 'True', 'Var': '', 'Help': '', 'Top': '280', 'Height': '70', 'Enable': 'True', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)'}","Layout","mBase","[]")
		self.pHotline=forms
		self.create("{'Left': '20', 'Tag': '', 'Events': '[]', 'Name': 'pHotline', 'Font': '', 'ParentsType': 'Layout', 'Text': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Width': '365', 'Visible': 'False', 'Var': '', 'Help': '', 'Top': '220', 'Height': '300', 'Enable': 'True', 'BackColor': '(1,1,1,1)'}","ListBox","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()