import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '-10', 'Picture': '', 'Visible': 'True', 'Height': '645', 'Text': 'Layout1', 'ParentsType': '', 'Font': '', 'Name': 'Activity', 'Width': '405', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Top': '-5', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '0', 'Picture': '', 'Visible': 'True', 'Height': '645', 'Text': 'Layout1', 'ParentsType': 'Layout', 'Font': '', 'Name': 'mBase', 'Width': '405', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Top': '0', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '0', 'Picture': 'MedicationsSubModule-6e7dd.png', 'Visible': 'True', 'Height': '645', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Name': 'Image1', 'Width': '405', 'BackColor': '(1,1,1,1)', 'Top': '0', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Image","mBase","[]")
		self.btnOrder=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '115', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Name': 'btnOrder', 'Width': '165', 'BackColor': '(0, 0.5947705885149066, 0.6256477024706841, 0.5)', 'Top': '195', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnBack=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '25', 'Picture': '', 'Visible': 'True', 'Height': '40', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Name': 'btnBack', 'Width': '55', 'BackColor': '(0, 0.5485275470322745, 0.40684617506831855, 0.5)', 'Top': '10', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnQr=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '330', 'Picture': '', 'Visible': 'True', 'Height': '40', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Name': 'btnQr', 'Width': '55', 'BackColor': '(0, 0.5485275470322745, 0.40684617506831855, 0.5)', 'Top': '10', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.lbl_startStop1=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '80', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lbl_startStop1', 'Width': '185', 'BackColor': '(1,1,1,1)', 'Top': '260', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDesc1=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '30', 'Picture': '', 'Visible': 'True', 'Height': '75', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDesc1', 'Width': '345', 'BackColor': '(1,1,1,1)', 'Top': '290', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDispenses1=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '265', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDispenses1', 'Width': '110', 'BackColor': '(1,1,1,1)', 'Top': '260', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lbl_startStop2=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '80', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lbl_startStop2', 'Width': '185', 'BackColor': '(1,1,1,1)', 'Top': '390', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDispenses2=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '265', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDispenses2', 'Width': '110', 'BackColor': '(1,1,1,1)', 'Top': '390', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDesc2=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '30', 'Picture': '', 'Visible': 'True', 'Height': '75', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDesc2', 'Width': '345', 'BackColor': '(1,1,1,1)', 'Top': '420', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lbl_startStop3=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '80', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lbl_startStop3', 'Width': '185', 'BackColor': '(1,1,1,1)', 'Top': '520', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDispenses3=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '265', 'Picture': '', 'Visible': 'True', 'Height': '30', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDispenses3', 'Width': '110', 'BackColor': '(1,1,1,1)', 'Top': '520', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDesc3=forms
		self.create("{'Help': '', 'Var': '', 'Tag': '', 'Events': '[]', 'Left': '30', 'Picture': '', 'Visible': 'True', 'Height': '75', 'Text': '', 'ParentsType': 'Layout', 'Font': '', 'Alignment': '', 'Name': 'lblDesc3', 'Width': '345', 'BackColor': '(1,1,1,1)', 'Top': '550', 'Enable': 'True', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()