import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Var': '', 'Width': '415', 'Events': '[]', 'Text': 'Layout1', 'Name': 'Activity', 'Tag': '', 'Font': '', 'Height': '650', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '-5', 'Left': '-10', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Visible': 'True'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '405', 'Events': '[]', 'Text': 'Layout1', 'Name': 'mBase', 'Tag': '', 'Font': '', 'Height': '640', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '5', 'Left': '10', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Visible': 'True'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '400', 'Events': '[]', 'Text': '', 'Name': 'Image1', 'Tag': '', 'Font': '', 'Height': '645', 'Enable': 'True', 'Picture': 'ScheduleSubModule-004a0.png', 'Help': '', 'Top': '0', 'Left': '0', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Image","mBase","[]")
		self.btnBack=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '65', 'Events': '[]', 'Text': '', 'Name': 'btnBack', 'Tag': '', 'Font': '', 'Height': '55', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '5', 'Left': '20', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btnQr=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '65', 'Events': '[]', 'Text': '', 'Name': 'btnQr', 'Tag': '', 'Font': '', 'Height': '55', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '5', 'Left': '325', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btn1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '55', 'Events': '[]', 'Text': '', 'Name': 'btn1', 'Tag': '', 'Font': '', 'Height': '40', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '375', 'Left': '325', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btn2=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '55', 'Events': '[]', 'Text': '', 'Name': 'btn2', 'Tag': '', 'Font': '', 'Height': '40', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '435', 'Left': '325', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btn3=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '55', 'Events': '[]', 'Text': '', 'Name': 'btn3', 'Tag': '', 'Font': '', 'Height': '40', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '495', 'Left': '325', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btn4=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '55', 'Events': '[]', 'Text': '', 'Name': 'btn4', 'Tag': '', 'Font': '', 'Height': '40', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '555', 'Left': '325', 'BackColor': '(0, 0.9053607853154132, 0.9332871050854253, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.lblTitlea=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '230', 'Events': '[]', 'Text': '', 'Name': 'lblTitlea', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '380', 'Left': '90', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lblTitleb=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '230', 'Events': '[]', 'Text': '', 'Name': 'lblTitleb', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '440', 'Left': '90', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lblTitlec=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '230', 'Events': '[]', 'Text': '', 'Name': 'lblTitlec', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '500', 'Left': '90', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lblTitled=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '230', 'Events': '[]', 'Text': '', 'Name': 'lblTitled', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '560', 'Left': '90', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.Calendar1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '340', 'Events': '[]', 'Text': '', 'Name': 'Calendar1', 'Tag': '', 'Font': '', 'Height': '155', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '145', 'Left': '35', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Calendar","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()