from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=1366,h=768,title="WiredQT v1.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       		
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()
		self.US1001.Open=True
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.createwidget("{'Name': 'US1001', 'Port': '/dev/ttyS0', 'Height': '30', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '195', 'Tag': 'Activex', 'Picture': 'US100.png', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(0, 0.5936772525366727, 0.5523303861997128, 0.5)', 'Events': [[['DistanceAquired', 'self,dist_mm']]], 'Enable': 'True', 'Visible': 'True', 'Left': '185', 'Text': '', 'Width': '30'}",'US100','usercontrol',"[['DistanceAquired', 'self,dist_mm']]")
		self.createwidget("{'Name': 'Button1', 'Height': '50', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '245', 'Tag': '', 'Picture': '', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Events': '[clicked]', 'Enable': 'True', 'Visible': 'True', 'Left': '190', 'Text': 'Get Distance', 'Width': '135'}",'QPushButton','usercontrol',"[['clicked', 'self,e']]")
		self.createwidget("{'Name': 'Entry1', 'Alignment': '', 'Height': '30', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '195', 'Tag': '', 'Picture': '', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Events': [], 'Enable': 'True', 'Visible': 'True', 'Left': '240', 'Text': '0', 'Width': '170'}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'Label1', 'Alignment': '', 'Height': '30', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '65', 'Tag': '', 'Picture': '', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Events': [], 'Enable': 'True', 'Visible': 'True', 'Left': '185', 'Text': 'US100_TX <-> RasPI_TX', 'Width': '195'}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'Label2', 'Alignment': '', 'Height': '30', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '105', 'Tag': '', 'Picture': '', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Events': [], 'Enable': 'True', 'Visible': 'True', 'Left': '185', 'Text': 'US100_RX <-> Raspi_RX', 'Width': '195'}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'Label3', 'Alignment': '', 'Height': '30', 'Var': '', 'Font': '', 'ParentsType': '', 'Top': '145', 'Tag': '', 'Picture': '', 'Help': '', 'ForeColor': '(0,0,0,1)', 'BackColor': '(1,1,1,1)', 'Events': [], 'Enable': 'True', 'Visible': 'True', 'Left': '185', 'Text': 'Due to Wrong Label Design in US100', 'Width': '280'}",'QLabel','usercontrol',"[]")
	def Widget(self):
		return self
	def US1001_DistanceAquired(self,dist_mm):
		self.Entry1.Text=dist_mm
		pass
	def Button1_clicked(self,e):
		self.US1001.GetDistance()
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())