import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Help': '', 'Height': '541', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': '', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Layout1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '50', 'Width': '643', 'Name': 'Activity', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Top': '30'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Help': '', 'Height': '520', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Layout2', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '444', 'Name': 'mBase', 'BackColor': '(1.00,1.00,1.00,1)', 'Top': '35'}","Layout","Activity","[]")
		import Timer
		self.Timer1=Timer.Handler
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': 'Timer.png', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Timer1', 'Enable': 'True', 'Tag': 'Activex', 'Visible': 'True', 'Left': '320', 'Width': '30', 'Interval': '1000', 'Name': 'Timer1', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Top': '335'}","Timer","mBase","[]")
		import Timer
		self.mytimer=Timer.Handler
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': 'Timer.png', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Timer2', 'Enable': 'True', 'Tag': 'Activex', 'Visible': 'True', 'Left': '275', 'Width': '30', 'Interval': '1000', 'Name': 'mytimer', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Top': '335'}","Timer","mBase","[]")
		self.Image1=forms
		self.create("{'Help': '', 'Height': '50', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Image1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '315', 'Width': '85', 'Name': 'Image1', 'BackColor': '(1,1,1,1)', 'Top': '280'}","Image","mBase","[]")
		self.Button1=forms
		self.create("{'Help': '', 'Height': '50', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Button1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '100', 'Name': 'Button1', 'BackColor': '(1,1,1,1)', 'Top': '300'}","Button","mBase","[]")
		self.Button2=forms
		self.create("{'Help': '', 'Height': '50', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Connect BT', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '170', 'Width': '100', 'Name': 'Button2', 'BackColor': '(1,1,1,1)', 'Top': '300'}","Button","mBase","[]")
		self.Label1=forms
		self.create("{'Help': '', 'Height': '70', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Power Logger App', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '345', 'Alignment': '', 'Name': 'Label1', 'BackColor': '(1,1,1,1)', 'Top': '30'}","Label","mBase","[]")
		self.Label2=forms
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'V', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '220', 'Alignment': '', 'Name': 'Label2', 'BackColor': '(1,1,1,1)', 'Top': '125'}","Label","mBase","[]")
		self.Label3=forms
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'A', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '220', 'Alignment': '', 'Name': 'Label3', 'BackColor': '(1,1,1,1)', 'Top': '165'}","Label","mBase","[]")
		self.Label4=forms
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'W', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '220', 'Alignment': '', 'Name': 'Label4', 'BackColor': '(1,1,1,1)', 'Top': '200'}","Label","mBase","[]")
		self.Label5=forms
		self.create("{'Help': '', 'Height': '30', 'Events': '[[, ]]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'WH', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '220', 'Alignment': '', 'Name': 'Label5', 'BackColor': '(1,1,1,1)', 'Top': '240'}","Label","mBase","[]")
		self.Button3=forms
		self.create("{'Help': '', 'Height': '35', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Button3', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '55', 'Width': '80', 'Name': 'Button3', 'BackColor': '(1,1,1,1)', 'Top': '360'}","Button","mBase","[]")
		self.Layout1=forms
		self.create("{'Help': '', 'Height': '40', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Layout1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '115', 'Width': '75', 'Name': 'Layout1', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Top': '405'}","Layout","mBase","[]")
		self.Label6=forms
		self.create("{'Help': '', 'Height': '25', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': '^', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '25', 'Width': '20', 'Alignment': '', 'Name': 'Label6', 'BackColor': '(1,1,1,1)', 'Top': '5'}","Label","Layout1","[]")
		self.Layout2=forms
		self.create("{'Help': '', 'Height': '40', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'v', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '115', 'Width': '75', 'Name': 'Layout2', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Top': '455'}","Layout","mBase","[]")
		self.Label7=forms
		self.create("{'Help': '', 'Height': '25', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'v', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '25', 'Width': '20', 'Alignment': '', 'Name': 'Label7', 'BackColor': '(1,1,1,1)', 'Top': '5'}","Label","Layout2","[]")
		self.Layout3=forms
		self.create("{'Help': '', 'Height': '40', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Layout1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '40', 'Width': '60', 'Name': 'Layout3', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Top': '430'}","Layout","mBase","[]")
		self.Label8=forms
		self.create("{'Help': '', 'Height': '25', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': '<', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '25', 'Width': '15', 'Alignment': '', 'Name': 'Label8', 'BackColor': '(1,1,1,1)', 'Top': '5'}","Label","Layout3","[]")
		self.Layout4=forms
		self.create("{'Help': '', 'Height': '40', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': 'Layout1', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '205', 'Width': '70', 'Name': 'Layout4', 'BackColor': '(0, 0.4361869060461, 0.42905835405256687, 0.5)', 'Top': '430'}","Layout","mBase","[]")
		self.Label9=forms
		self.create("{'Help': '', 'Height': '25', 'Events': '[]', 'Picture': '', 'ParentsType': 'Layout', 'ForeColor': '(0,0,0,1)', 'Var': '', 'Font': '', 'Text': '>', 'Enable': 'True', 'Tag': '', 'Visible': 'True', 'Left': '20', 'Width': '25', 'Alignment': '', 'Name': 'Label9', 'BackColor': '(1,1,1,1)', 'Top': '5'}","Label","Layout4","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()