from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		self.SerialPort0.Open=True

		self.parse=Parser("WTA","\r",1)

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'Events': '[clicked]', 'Enable': 'True', 'Picture': '', 'Tag': '', 'Height': '45', 'Font': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'Text': 'Serial.println Test', 'Top': '127', 'Width': '119', 'Help': '', 'Name': 'QPushButton1', 'Left': '63', 'BackColor': '(1,1,1,0.25)', 'Visible': 'True', 'ParentsType': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'Events': [[['CommEvent', 'self,arg1']], [['CommEvent', 'self,arg1,arg2']]], 'Enable': 'True', 'Picture': '', 'Tag': 'Activex', 'Height': '29', 'Open': 'False', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Text': '', 'Top': '29', 'Help': '', 'Port': 'COM7', 'Width': '97', 'Var': '', 'Setting': '9600,n,8,1', 'Name': 'SerialPort0', 'Left': '62', 'BackColor': '(1,1,1,0.25)', 'Visible': 'False', 'ParentsType': ''}",'SerialPort','usercontrol',"[['CommEvent', 'self,arg1'], ['CommEvent', 'self,arg1,arg2']]")
		self.createwidget("{'Events': [], 'Enable': 'True', 'Picture': '', 'Tag': '', 'Visible': 'True', 'Font': '', 'Var': '', 'ForeColor': '(0,0,0,1)', 'Text': 'WTARocky Nuarin', 'Top': '92', 'Width': '116', 'Help': '', 'Name': 'QLineEdit2', 'BackColor': '(1,1,1,0.25)', 'Left': '64', 'Height': '27', 'ParentsType': ''}",'QLineEdit','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
	def QPushButton1_clicked(self,arg1):
		self.SerialPort0.println(self.QLineEdit2.Text)
		pass
	def SerialPort0_CommEvent(self,arg1):
		while(arg1.available()):
			ch=arg1.read().decode()
			print(ch)
			if self.parse.available(ch):
				print(self.parse.data)
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
