from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=1020,h=800,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'ParentsType': '', 'Name': 'QSpinBox1', 'Width': '100', 'Top': '83', 'Var': '', 'Font': '', 'Help': '', 'Left': '398', 'Height': '100', 'Visible': 'True', 'Tag': '', 'ForeColor': '(0,0,0,1)', 'Text': '0', 'Enable': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Picture': ''}",'QSpinBox','usercontrol',"[]")
		self.createwidget("{'ParentsType': '', 'Name': 'QDateTimeEdit6', 'Width': '121', 'Top': '56', 'Var': '', 'Picture': '', 'Help': '', 'Height': '21', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Text': '1/1/2000 12:00 AM', 'Left': '651', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Tag': ''}",'QDateTimeEdit','usercontrol',"[]")
		self.createwidget("{'ParentsType': '', 'Name': 'QPushButton4', 'Left': '24', 'Top': '81', 'Var': '', 'ForeColor': '(0,0,0,1)', 'Help': '', 'Width': '100', 'Height': '100', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Text': 'QPushButton4', 'BackColor': '(1,1,1,0.25)', 'Events': '[clicked]', 'Picture': '', 'Tag': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'ParentsType': '', 'Name': 'myctl2', 'Left': '514', 'Top': '292', 'Var': '', 'ForeColor': '(0,0,0,1)', 'Help': '', 'Width': '165', 'Height': '109', 'Visible': 'True', 'Tag': 'Activex', 'Font': '', 'Text': '', 'Enable': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Picture': ''}",'myctl','usercontrol',"[]")
		self.createwidget("{'ParentsType': '', 'Name': 'SerialPort0', 'Width': '200', 'Top': '63', 'Setting': '9600,n,8,1', 'Var': '', 'Font': '', 'Help': '', 'Left': '135', 'Height': '200', 'Port': 'COM2', 'Visible': 'True', 'Enable': 'False', 'ForeColor': '(0,0,0,1)', 'Text': '', 'Open': 'False', 'BackColor': '(1,1,1,0.25)', 'Events': [[['CommEvent', 'self,arg1,arg2']]], 'Picture': '', 'Tag': 'Activex'}",'SerialPort','usercontrol',"[['CommEvent', 'self,arg1,arg2']]")
		self.createwidget("{'ParentsType': '', 'Name': 'myctl3', 'Left': '689', 'Top': '305', 'Var': '', 'ForeColor': '(0,0,0,1)', 'Help': '', 'Width': '160', 'Height': '110', 'Visible': 'True', 'Tag': 'Activex', 'Font': '', 'Text': '', 'Enable': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Picture': ''}",'myctl','usercontrol',"[]")
		self.createwidget("{'ParentsType': '', 'Name': 'QLabel5', 'Width': '632', 'Top': '2', 'Var': '', 'Font': '', 'Help': '', 'Left': '4', 'Height': '451', 'Visible': 'True', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Text': '', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Picture': 'ESP8266-Pinout.jpg', 'Tag': ''}",'QLabel','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
	def SerialPort0_CommEvent(self,arg1,arg2):
		pass
	def QPushButton4_clicked(self,arg1):

		self.myctl2.Left+=100
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
