from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=1366,h=600,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       
		self.sch=Scheduler(500)#500 ms

		self.sch.Start()
		self._text=''
		self._usercontrolproperty=''
		
	@property	
	def usercontrolproperty(self):
		return self._usercontrolproperty
	@usercontrolproperty.setter	
	def usercontrolproperty(self,value):
		self._usercontrolproperty=value
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})
	def activeXcreated(self,*args):
		pass
	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 	
	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.createwidget("{'Var': '', 'Help': '', 'Width': '100', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '50', 'Visible': 'True', 'Top': '280', 'ParentsType': '', 'Tag': '', 'Text': 'DisplayALL', 'Left': '85', 'Name': 'Button1', 'BackColor': '(1,1,1,1)', 'Events': '[clicked]', 'Picture': ''}",'QPushButton','usercontrol',"[['clicked', 'self,e']]")
		self.createwidget("{'Var': '', 'Help': '', 'D5': '16', 'Width': '30', 'D7': '21', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'RS': '13', 'Height': '30', 'D6': '20', 'Visible': 'True', 'Top': '345', 'ParentsType': '', 'D4': '26', 'E': '19', 'Tag': 'Activex', 'Text': '', 'Left': '310', 'Name': 'LiquidCrystal1', 'BackColor': '(0, 0.2427150688328712, 0.24508658857095755, 0.5)', 'Events': [], 'Picture': ''}",'LiquidCrystal','usercontrol',"[]")
		self.createwidget("{'Var': '', 'Help': '', 'Width': '100', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '50', 'Visible': 'True', 'Top': '105', 'ParentsType': '', 'Tag': '', 'Text': 'begin', 'Left': '85', 'Name': 'Button2', 'BackColor': '(1,1,1,1)', 'Events': '[clicked]', 'Picture': ''}",'QPushButton','usercontrol',"[['clicked', 'self,e']]")
		self.createwidget("{'Var': '', 'Help': '', 'Width': '100', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '50', 'Visible': 'True', 'Top': '215', 'ParentsType': '', 'Tag': '', 'Text': 'print', 'Left': '85', 'Name': 'Button3', 'BackColor': '(1,1,1,1)', 'Events': '[clicked]', 'Picture': ''}",'QPushButton','usercontrol',"[['clicked', 'self,e']]")
		self.createwidget("{'Var': '', 'Help': '', 'Width': '170', 'Alignment': '', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '30', 'Visible': 'True', 'Top': '235', 'ParentsType': '', 'Tag': '', 'Text': 'WireThemAll', 'Left': '195', 'Name': 'Entry1', 'BackColor': '(1,1,1,1)', 'Events': [], 'Picture': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Var': '', 'Help': '', 'Width': '100', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '50', 'Visible': 'True', 'Top': '160', 'ParentsType': '', 'Tag': '', 'Text': 'setCursor', 'Left': '85', 'Name': 'Button4', 'BackColor': '(1,1,1,1)', 'Events': '[clicked]', 'Picture': ''}",'QPushButton','usercontrol',"[['clicked', 'self,e']]")
		self.createwidget("{'Var': '', 'Help': '', 'Width': '170', 'Alignment': '', 'Enable': 'True', 'Font': '', 'ForeColor': '(0,0,0,1)', 'Height': '30', 'Visible': 'True', 'Top': '175', 'ParentsType': '', 'Tag': '', 'Text': '0,0', 'Left': '195', 'Name': 'Entry2', 'BackColor': '(1,1,1,1)', 'Events': [], 'Picture': ''}",'QLineEdit','usercontrol',"[]")
	def Widget(self):
		return self
	def Button1_clicked(self,e):
		self.LiquidCrystal1.begin(4,20)
		self.LiquidCrystal1.setCursor(1,0)
		self.LiquidCrystal1.print("Hello1")
		self.LiquidCrystal1.setCursor(2,1)
		self.LiquidCrystal1.print("Hello2")
		self.LiquidCrystal1.setCursor(3,2)
		self.LiquidCrystal1.print("Hello3")
		self.LiquidCrystal1.setCursor(4,3)
		self.LiquidCrystal1.print("Hello4")
		
		pass
	def Button2_clicked(self,e):
		self.LiquidCrystal1.begin(20,4)
		pass
	def Button3_clicked(self,e):
		self.LiquidCrystal1.print(self.Entry1.Text)
		pass
	def Button4_clicked(self,e):
		col=eval("[" + self.Entry2.Text + "][0]")
		row=eval("[" + self.Entry2.Text + "][1]")
		self.LiquidCrystal1.setCursor(col,row)
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())