from PyQt5 import QtCore, QtWidgets,QtMultimedia
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		initUI(self,param,w=400,h=400,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(500)#500 ms
		self.sch.Start()
		


		
	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):		self.createwidget("{'Left': '189', 'Picture': '', 'Width': '119', 'Top': '76', 'Events': '[clicked]', 'Font': '', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Name': 'QPushButton3', 'Text': 'Start', 'ForeColor': '(0,0,0,1)', 'Tag': '', 'Enable': 'True', 'Var': '', 'ParentsType': '', 'Height': '45', 'Help': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
		self.createwidget("{'Left': '62', 'Tag': 'Activex', 'Width': '100', 'Top': '67', 'Events': [[['Tick', 'self,arg1']]], 'Font': '', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Name': 'Timer2', 'Text': '', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Enable': 'True', 'Var': '', 'ParentsType': '', 'Height': '100', 'Interval': '1000', 'Help': ''}",'Timer','usercontrol',"[['Tick', 'self,arg1']]")
		self.createwidget("{'Left': '189', 'Tag': '', 'Width': '119', 'Top': '129', 'Events': '[clicked]', 'Font': '', 'Height': '45', 'BackColor': '(1,1,1,0.25)', 'Name': 'QPushButton1', 'Text': 'Stop', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Enable': 'True', 'Var': '', 'ParentsType': '', 'Visible': 'True', 'Help': ''}",'QPushButton','usercontrol',"[['clicked', 'self,arg1']]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
	def QPushButton1_clicked(self,arg1):

		self.Timer2.Enable=False
	def QPushButton3_clicked(self,arg1):
		self.Timer2.Enable=True
	def Timer2_Tick(self):
		print(NowToString())
		pass
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
